/// Flutter icons AgriVIcons
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AgriVIcons
///      fonts:
///       - asset: fonts/AgriVIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AgriVIcons {
  AgriVIcons._();

  static const _kFontFam = 'AgriVIcons';
  static const String? _kFontPkg = null;

  static const IconData icon__1_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_icon_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
